Update actions

diff --git a/.github/workflows/publish-github-release.yml b/.github/workflows/publish-github-release.yml
--- a/.github/workflows/publish-github-release.yml
+++ b/.github/workflows/publish-github-release.yml
@@ -4,18 +4,33 @@ on:
   push:
     # Sequence of patterns matched against refs/tags
     tags:
-      - 'v*' # Push events to matching v*, i.e. v1.0.0
+      - '*.*.*' # Push events to matching semantic version tags 1.0.0, etc.
 
 jobs:
-  build:
-    name: Create GitHub Release
+  semver-check:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4.1.1
+      - name: Check SemVer tag
+        run: |
+          TAG_NAME=$(git tag --points-at ${{ github.sha }})
+          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Valid SemVer tag: $TAG_NAME"
+          else
+            echo "Invalid SemVer tag: $TAG_NAME"
+            exit 1
+          fi
+  build:
+    name: Create GitHub Release
+    runs-on: ubuntu-latest
+    needs: semver-check
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
       - name: Create Release
         id: create_release
-        uses: actions/create-release@v1
+        uses: actions/create-release@latest
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
         with:
diff --git a/.github/workflows/publish-to-pypi.yml b/.github/workflows/publish-to-pypi.yml
--- a/.github/workflows/publish-to-pypi.yml
+++ b/.github/workflows/publish-to-pypi.yml
@@ -4,19 +4,35 @@ on:
   push:
     # Sequence of patterns matched against refs/tags
     tags:
-      - 'v*'# Push events to matching v*, i.e. v1.0.0
+      - '*.*.*' # Push events to matching semantic version tags 1.0.0, etc.
 
 jobs:
+  semver-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
+      - name: Check SemVer tag
+        run: |
+          TAG_NAME=$(git tag --points-at ${{ github.sha }})
+          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Valid SemVer tag: $TAG_NAME"
+          else
+            echo "Invalid SemVer tag: $TAG_NAME"
+            exit 1
+          fi
   build-and-publish:
     name: Build and publish to PyPI
     runs-on: ubuntu-latest
+    needs: semver-check
     steps:
-      - uses: actions/checkout@master
+      - name: Checkout code
+        uses: actions/checkout@4.1.1
       - name: Set up Python 3.10
-        uses: actions/setup-python@v3
+        uses: actions/setup-python@v4.7.1
         with:
           python-version: "3.10"
-      - name: Install pypa/build
+      - name: Install build requirements
         run: >-
           python -m
           pip install -U
